# Generated by Django 5.1.6 on 2025-03-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0004_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.teacher",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
