# Generated by Django 5.1.6 on 2025-03-05 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0005_attendance_teacher_teacher_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.teacher",
            ),
        ),
    ]
